[supervisord]
nodaemon=false
logfile=/home/kevin850515123456789/stock/logs/supervisord.log
pidfile=/home/kevin850515123456789/stock/logs/supervisord.pid
childlogdir=/home/kevin850515123456789/stock/logs

[unix_http_server]
file=/home/kevin850515123456789/stock/logs/supervisor.sock

[supervisorctl]
serverurl=unix:///home/kevin850515123456789/stock/logs/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:trading-app]
command=/home/kevin850515123456789/stock/venv/bin/python /home/kevin850515123456789/stock/app.py
directory=/home/kevin850515123456789/stock
autostart=true
autorestart=true
startretries=999
stdout_logfile=/home/kevin850515123456789/stock/logs/app_out.log
stderr_logfile=/home/kevin850515123456789/stock/logs/app_err.log

[program:trading-ngrok]
command=/home/kevin850515123456789/stock/bin/ngrok http --url=oscillatory-robbyn-circularly.ngrok-free.dev 5000 --config /home/kevin850515123456789/.config/ngrok/ngrok.yml
autostart=true
autorestart=true
startretries=999
stdout_logfile=/home/kevin850515123456789/stock/logs/ngrok_out.log
stderr_logfile=/home/kevin850515123456789/stock/logs/ngrok_err.log
